### ISSUE TITLE
Update Track Metadata

### ISSUE THREAD

**Issue by whobutsb** [react-native-kit/react-native-track-player#154] opened 2018-02-28 22:29 UTC
Hello!  Is there a method or a way to update the current Track metadata?  I'am building an audio player that plays IceCast streams that are continuous and would be considered 1 track.  It would be nice to update the metadata of the track so that album cover, title, artist, etc are updated on the system audio control.

**Comment by Guichaguri** [comment] 2018-03-02 23:26
Duplicate of #93

**Closed by Guichaguri** 2018-03-02 23:26 UTC
Labels: Duplicate
