### ISSUE TITLE
[iOS] Can't play track store on Firebase

### ISSUE THREAD

**Issue by AylanBoscarino** [react-native-kit/react-native-track-player#617] opened 2019-06-04 23:06 UTC
# Configuration

Version:
1.1.4

React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
      Memory: 21.87 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.4 => 16.8.4 
      react-native: 0.59.3 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

# Issue

I'm using the Firebase Storage module to store my audio files. The problem is that Firebase Storage uses %2F to indicate it's internal file structure in the URL and it's being encoded to '/'.

This problem only occurs in iOS, the Android version of the app works as expected.

This is the audio I'm working on: 
https://firebasestorage.googleapis.com/v0/b/hupper-mobile.appspot.com/o/audio_meditation%2Fanxiety%2FTeste_Raffael%20Marfara%CC%81_20%20segundos.mp3?alt=media&token=55aff5c0-1af7-4a8b-b4a2-f450c12f181c

**Comment by AylanBoscarino** [comment] 2019-06-07 15:06
I found the problem was that the model MediaURL.swift was encoding and decoding the URL it was given. 
I'm not swift programmer  and don't have the time to learn right now so I just commented some lines until it worked.

I forked the library just so I can run it in my project ASAP but I hope to find a proper solution.

```swift
import Foundation

struct MediaURL {
    let value: URL
    let isLocal: Bool
    private let originalObject: Any
    
    init?(object: Any?) {
        guard let object = object else { return nil }
        originalObject = object
        
        if let localObject = object as? [String: Any] {
            let uri = localObject["uri"] as! String
            isLocal = uri.contains("http") ? false : true
            let encodedURI = uri.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!
            value = URL(string: encodedURI.replacingOccurrences(of: "file://", with: ""))!
        } else {
            // ESSE TRECHO FOI COMENTADO PARA FUNCIONAR COM O FIREBASE STORAGE
            let url = object as! String
            // let urlencoded = url.removingPercentEncoding
            isLocal = url.lowercased().hasPrefix("file://")
            if true
            // ESSE TRECHO FOI COMENTADO PARA FUNCIONAR COM O FIREBASE STORAGE
            // let encoded = urlencoded!.addingPercentEncoding(withAllowedCharacters: CharacterSet.urlFragmentAllowed
            //     .union(.urlHostAllowed)
            //     .union(.urlPasswordAllowed)
            //     .union(.urlQueryAllowed)
            //     .union(.urlUserAllowed)) 
            {
                value = URL(string: url.replacingOccurrences(of: "file://", with: ""))!
            } else {
                value = URL(string: url.replacingOccurrences(of: "file://", with: ""))!
            }
        }
    }
}
```

**Comment by Guichaguri** [comment] 2019-06-21 02:26
Duplicate of #543

**Closed by Guichaguri** 2019-06-21 02:26 UTC
Labels: Duplicate, iOS
