### ISSUE TITLE
playing ogg on ios

### ISSUE THREAD

**Issue by Mahfa** [react-native-kit/react-native-track-player#395] opened 2019-01-15 02:17 UTC
hello and thanks for this great library 👍 
does this library support playing ogg files on ios ?
or if not how can i implement it ?

**Comment by Guichaguri** [comment] 2019-01-18 09:55
Not yet.
We have a number of issues asking about OGG on iOS, we'll keep a single one. Feel free to upvote/comment on it.

Duplicate of #207

**Closed by Guichaguri** 2019-01-18 09:55 UTC
Labels: Duplicate, iOS
