### ISSUE TITLE
Repeat track on queue

### ISSUE THREAD

**Issue by ithustle** [react-native-kit/react-native-track-player#481] opened 2019-03-09 10:17 UTC
Is there a way to repeat one track on queue of at least 4 tracks? 

If no, have you guys a plan to implement it?

**Comment by Guichaguri** [comment] 2019-03-09 15:33
Duplicate of #122

**Closed by Guichaguri** 2019-03-09 15:33 UTC
Labels: Duplicate

**Comment by ithustle** [comment] 2019-03-09 17:33
Unfortunetly it doesn't help me...

**Comment by Guichaguri** [comment] 2019-03-09 18:50
I'm unifying each suggestion in a single issue, it's supposed to help the project stay organized. If you want this feature, you should 👍 that issue instead.
