### ISSUE TITLE
Skip Crashes The App

### ISSUE THREAD

**Issue by thecodecafe** [react-native-kit/react-native-track-player#240] opened 2018-07-29 22:40 UTC
Every time I try to skip to a particular track the app just crashes, I don't get an error message, it just crashes, please find my sample code below.

```
async handleReloadQueue(song){
    // get next queue
    let queue = _.clone( song.data );

    // shuffle queue when shuffle is on and next queue is a list of songs
    if(this.props.playerSettings.shuffled && song.data.constructor == Array ){
        queue = _.shuffle( queue );
    }

    // clears current queue
    TrackPlayer.reset();

    // reload queue
    await TrackPlayer.add(queue);

    // skip to starting track if specified
    if(song.startFrom && _.findIndex(queue, {id: song.startFrom}) != -1){
        // skip to the starting track
        await TrackPlayer.skip(`${song.startFrom}`);
    }

    // start player
    TrackPlayer.play();
}
```

Am I doing something wrong here? Have added the skip capability.

**Comment by jdrorrer** [comment] 2018-07-30 00:18
It may not have a track to skip to yet since `.add` is asynchronous. I'd say try adding `await` before your `Trackplayer.add()` call as well.

**Comment by thecodecafe** [comment] 2018-07-30 05:59
@jdrorrer added await but still crashes.

**Comment by jdrorrer** [comment] 2018-07-30 13:57
@thecodecafe where are you getting nextProps from in this case? Is it throwing an undefined error?

**Comment by thecodecafe** [comment] 2018-07-30 14:04
@jdrorrer O sorry forgot to update the code in the question, removed that, it was initially in Reacts `component will receive props lifecycle method`

**Comment by jdrorrer** [comment] 2018-07-30 20:41
@thecodecafe Have you tried just `.skipToNext()` instead without passing in song.startFrom? If skipToNext works fine, then I'm guessing there may be something off with song.startFrom.

**Comment by dcvz** [comment] 2018-10-21 11:47
Are you still facing this? Could you provide the crash log?

**Comment by Jayiitb** [comment] 2018-12-12 12:38
@dcvz  Still the issue is persistent with version 1.0.0
I got this error when I am trying to `skip` to the song, added to the queue, After a network failure on the previous song played.

**Comment by Guichaguri** [comment] 2019-01-20 15:14
Which platform are you facing this issue? Android or iOS?

**Comment by Guichaguri** [comment] 2019-01-21 09:47
Seems like a duplicate of #364. I'll keep that one instead.

**Closed by Guichaguri** 2019-01-21 09:47 UTC

**Comment by shubhambabar-007** [comment] 2023-11-08 06:43
Facing same issue when try to use TrackPlayer.skip(), 
the error is: Attempt to invoke virtual method 'doublejava.lang.Double.doubleValue()' on a null object reference
