### ISSUE TITLE
metadata(artist, title) from internet radio stream

### ISSUE THREAD

**Issue by gHashTag** [react-native-kit/react-native-track-player#439] opened 2019-02-09 16:55 UTC
Is it possible to get metadata(artist, title) from internet radio stream?

**Comment by moonstruck** [comment] 2019-02-09 18:50
A [pull request](https://github.com/react-native-kit/react-native-track-player/pull/384) available in this regard.

**Comment by Guichaguri** [comment] 2019-02-24 18:16
Duplicate of #192.

**Closed by Guichaguri** 2019-02-24 18:16 UTC
Labels: Duplicate
