### ISSUE TITLE
Network stream with .opus stops working after playing first track

### ISSUE THREAD

**Issue by kirankuyate** [react-native-kit/react-native-track-player#623] opened 2019-06-09 16:28 UTC
# Configuration

React Native Environment Info:
    System:
      OS: Windows 8
      CPU: (8) x64 Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
      Memory: 6.14 GB / 15.88 GB
    Binaries:
      Yarn: 1.12.3 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

What `react-native-track-player` version are you using?
1.1.4

# Issue
Trying to play a stream of .opus but it just stops working after playing first track

# Code

```
     await TrackPlayer.add({
        id: "123",
        url: MY_STREAM_URL,
        title: Title,
        artist: Artist,
        artwork: require("artwork")
      });

      TrackPlayer.updateOptions({
        capabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE,
          TrackPlayer.CAPABILITY_STOP
        ],
        compactCapabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE,
          TrackPlayer.CAPABILITY_STOP
        ],
        stopWithApp: true,
        waitForBuffer: true,
      });

      TrackPlayer.play();
```

**Comment by Guichaguri** [comment] 2019-06-09 23:14
What do you mean by "stop working"? Does it stops playing? Do you have any crash logs?

**Comment by kirankuyate** [comment] 2019-06-10 02:49
> 
> 
> What do you mean by "stop working"? Does it stops playing? Do you have any crash logs?

@Guichaguri App doesn't crash, it just stops playing audio stream after playing first song track.

**Comment by kirankuyate** [comment] 2019-06-16 06:43
@Guichaguri Here is additional log which may help you understand the problem,

![image](https://user-images.githubusercontent.com/8225086/59560465-f92f4c80-902f-11e9-9b9b-2e1151ad9c58.png)

**Comment by kirankuyate** [comment] 2019-07-17 04:09
@Guichaguri Any updates with this issue?

**Comment by Guichaguri** [comment] 2019-08-03 19:29
Duplicate of #473

**Closed by Guichaguri** 2019-08-03 19:29 UTC
Labels: Android, Duplicate
