### ISSUE TITLE
Track URL is wrong on release apk that cause player not to work

### ISSUE THREAD

**Issue by MohammadElKhatib** [react-native-kit/react-native-track-player#155] opened 2018-03-02 14:44 UTC
after running on dev and all is working good then i exported a signed apk as release but the player doesn't work after debugging, and the url is showing as number only here is the track output:

[ { id: '0',
                                                    url: **21**,
                                                    title: 'test',
                                                    artist: 'test',
                                                    album: 'test',
                                                    genre: 'test',
                                                    date: '2014-05-20T07:00:00+00:00',
                                                    artwork: 10 },
                                                  { id: '1',
                                                    url: **22**,
                                                    title: 'test',
                                                    artist: 'test',
                                                    album: 'test',
                                                    genre: 'test',
                                                    date: '2014-05-20T07:00:00+00:00',
                                                    artwork: 10 },
                                                  { id: '2',
                                                    url: **23**,
                                                    title: 'test,
                                                    artist: 'test,
                                                    album: 'test',
                                                    genre: 'test',
                                                    date: '2014-05-20T07:00:00+00:00',
                                                    artwork: 10 }]

**Comment by Guichaguri** [comment] 2018-03-02 23:24
Duplicate of #134

**Closed by Guichaguri** 2018-03-02 23:24 UTC
Labels: Android, Duplicate
