### ISSUE TITLE
import TrackPlayer from 'react-native-track-player' throwing the error Native module cannot be null

### ISSUE THREAD

**Issue by plgrazon** [react-native-kit/react-native-track-player#373] opened 2018-12-28 10:09 UTC
import TrackPlayer from 'react-native-track-player' throwing the error Native module cannot be null

Im building a react-native ios app and this is the error that I'm getting. I linked the module and it is still giving me this error.

**Comment by Guichaguri** [comment] 2018-12-29 14:46
Try removing the module and linking it again.

**Comment by plgrazon** [comment] 2018-12-29 15:42
Still giving me the error.

**Comment by moonstruck** [comment] 2018-12-29 15:45
@plgrazon Which platform?

**Comment by plgrazon** [comment] 2018-12-29 16:49
> @plgrazon Which platform?

iOS sir.

**Comment by jonaird** [comment] 2018-12-31 23:32
I'm having the same problem...

**Comment by jonaird** [comment] 2018-12-31 23:52
I'm getting the same problem even with a fresh react-native init and a single import line...

**Comment by mohitpanjwani** [comment] 2019-01-08 13:53
Same issue here! Did you guys figure out a solution for this yet?

**Comment by plgrazon** [comment] 2019-01-08 16:47
No soulutions yet :(

**Comment by mohitpanjwani** [comment] 2019-01-09 03:11
I managed to make my audio streaming app using a different package: react-native-video

And it seems to be woeking as expected.

**Comment by plgrazon** [comment] 2019-01-09 04:05
> I managed to make my audio streaming app using a different package: react-native-video
> 
> And it seems to be working as expected.

I didn't know react-native-video can stream music! Do you mind sharing your repo?

**Comment by jonaird** [comment] 2019-01-09 16:42
I've been trying react-native-video as well. The problem is that it doesn't hook into external controls (such as on the lock screen).

**Comment by cactis** [comment] 2019-01-16 01:09
> I've been trying react-native-video as well. The problem is that it doesn't hook into external controls (such as on the lock screen).

I've found react-native-video in android no sound, no any errors (iOS is fine)
now react-native-track-player get "Native module cannot be null" in iOS(Android is ok) ><

**Comment by mohitpanjwani** [comment] 2019-01-16 08:38
> > I managed to make my audio streaming app using a different package: react-native-video
> > And it seems to be working as expected.
> 
> I didn't know react-native-video can stream music! Do you mind sharing your repo?

Sorry for the late reply but I took some code/inspiration from this repo: https://github.com/aakashns/reactmusic

It seems to work perfectly! For music controls I used https://github.com/tanguyantoine/react-native-music-control ( Same package that many have suggested above), However, you will have to do bind the events manually from react-native-video with the music-control events

It works perfectly for IOS and Android both.

**Comment by mohitpanjwani** [comment] 2019-01-16 08:39
> > I've been trying react-native-video as well. The problem is that it doesn't hook into external controls (such as on the lock screen).
> 
> I've found react-native-video in android no sound, no any errors (iOS is fine)
> now react-native-track-player get "Native module cannot be null" in iOS(Android is ok) ><

You should downgrade `react-native-video` to 4.2 by running the following command: 
`npm install react-native-video@4.2` and then rebuild the android app. 

That solves it 👍

**Comment by jonaird** [comment] 2019-01-16 22:21
Does anyone know of any good tutorials for react-native-music-control?

**Comment by Guichaguri** [comment] 2019-01-17 10:20
This is going too off topic. I'll keep it locked until the issue is fixed.

**Comment by dcvz** [comment] 2019-01-19 15:19
I've just published a [new version - 1.1.0](https://github.com/react-native-kit/react-native-track-player/releases/tag/v1.1.0), could you try again? The example is working fine and so is another project which is using this package.

**Comment by ataravati** [comment] 2019-01-19 18:48
@dcvz I still get the same error.

**Comment by dcvz** [comment] 2019-01-19 19:31
Sorry, but want the thread to be easy to follow and a solution to the actual problem found.

**Comment by ataravati** [comment] 2019-01-19 19:52
@dcvz Adding the swift file resolved the issue for me. Thanks!

**Comment by cactis** [comment] 2019-01-20 02:59
> I've just published a [new version - 1.1.0](https://github.com/react-native-kit/react-native-track-player/releases/tag/v1.1.0), could you try again? The example is working fine and so is another project which is using this package.

still same error (Native module cannot be null, iOS only)

**Comment by jonaird** [comment] 2019-01-20 03:01
adding the swift file fixed for me as well.

**Comment by dcvz** [comment] 2019-01-20 11:42
> Could ya'll try doing step 1 from the troubleshooting of the install section [here](https://github.com/react-native-kit/react-native-track-player/wiki/Installation#troubleshooting)?
> 
> The part titled: `library not found for -lswiftCoreAudio for architecture x86_64`

@cactis did you see this message?

**Comment by dcvz** [comment] 2019-01-20 11:55
I've update the [Wiki](https://github.com/react-native-kit/react-native-track-player/wiki/Installation) with an easier way to enable Swift support. If you follow the instructions, we should no longer see this issue.

I'll be closing this issue now 😃

**Closed by dcvz** 2019-01-20 11:55 UTC
Labels: Bug, iOS

**Comment by gazedash** [comment] 2019-01-24 12:02
Please specify the required Swift version. Xcode doesn't show helpful error messages.

**Comment by ericwrobinson** [comment] 2019-03-06 01:01
@dcvz would you still have that information you are linking to somewhere? It appears the wiki information has been removed and I cannot see what the 'Swift File' is that is fixing it.

**Comment by curiousdustin** [comment] 2019-03-06 01:33
Wiki was moved to here:
https://react-native-kit.github.io/react-native-track-player/install/

**Comment by ericwrobinson** [comment] 2019-03-06 01:42
> Wiki was moved to here:
> https://react-native-kit.github.io/react-native-track-player/install/

haha thank you, I just found the reference [here](https://react-native-kit.github.io/react-native-track-player/install/#troubleshooting) and it worked! Thanks!

**Comment by zuby64** [comment] 2022-12-21 06:08
I am still facing this issue,any solution for it ?

**Comment by martinmidtsund** [comment] 2022-12-21 10:13
@zuby64 https://react-native-track-player.js.org/docs/troubleshooting and see how to configure a bridging header.

**Comment by zuby64** [comment] 2022-12-21 15:27
Is this library compatible for reac-native-tvos?

**Comment by martinmidtsund** [comment] 2022-12-21 21:35
@zuby64 I would guess not, ref https://react-native-track-player.js.org/docs/basics/platform-support

**Comment by zuby64** [comment] 2022-12-23 06:51
Ok, thanks.
