### ISSUE TITLE
Android bug onStartCommand

### ISSUE THREAD

**Issue by GH974** [react-native-kit/react-native-track-player#380] opened 2019-01-03 10:01 UTC
Hi, I found new bug in android.

LOG ERROR IN GOOGLE PLAY DEV
_Samsung Galaxy S8 (dreamlte), Android 8.0_
Caused by: java.lang.NullPointerException: 
  at com.guichaguri.trackplayer.service.MusicService.onStartCommand (MusicService.java:68)
  at android.app.ActivityThread.handleServiceArgs (ActivityThread.java:3677)

**Comment by Guichaguri** [comment] 2019-01-03 10:03
Duplicate of #351

**Closed by Guichaguri** 2019-01-03 10:03 UTC
Labels: Android, Duplicate
