### ISSUE TITLE
Updating Track Data

### ISSUE THREAD

**Issue by JDBlackman** [react-native-kit/react-native-track-player#194] opened 2018-05-07 17:51 UTC
Is it possible  to be able to update the track data without playing the next track. I am using this to play a radio stream and since metadata is currently not supported, I would like to manually update the notification.

**Comment by Guichaguri** [comment] 2018-05-07 22:06
Duplicate of #93 -- Or even #192

**Closed by Guichaguri** 2018-05-07 22:06 UTC
Labels: Duplicate
