### ISSUE TITLE
[BUG] App crashed on android with sdk 26, emulator android 7.0

### ISSUE THREAD

**Issue by ananevam** [react-native-kit/react-native-track-player#166] opened 2018-03-27 09:59 UTC
demo - https://github.com/ananevam/RNTrackPlayerCrash
app/build.gradle - https://pastebin.com/hvCYAjrC
app/android/build.gradle - https://pastebin.com/mMb80n4H
adb logcat - https://pastebin.com/r7FD7hE0

TrackPlayer.setupPlayer - crash

03-27 09:52:26.335 26202 26202 D ReactNativeTrackPlayer: Service init
03-27 09:52:26.336 26202 26202 I art     : Rejecting re-init on previously-failed class java.lang.Class<guichaguri.trackplayer.player.players.ExoPlayback>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/ExoPlayer$EventListener;
03-27 09:52:26.336 26202 26202 I art     :   at void guichaguri.trackplayer.logic.services.PlayerService.onCreate() (PlayerService.java:74)
03-27 09:52:26.336 26202 26202 I art     :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3162)
03-27 09:52:26.336 26202 26202 I art     :   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
03-27 09:52:26.336 26202 26202 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1550)
03-27 09:52:26.336 26202 26202 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
03-27 09:52:26.336 26202 26202 I art     :   at void android.os.Looper.loop() (Looper.java:154)
03-27 09:52:26.336 26202 26202 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
03-27 09:52:26.336 26202 26202 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
03-27 09:52:26.336 26202 26202 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:866)
03-27 09:52:26.336 26202 26202 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:756)
03-27 09:52:26.336 26202 26202 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.ExoPlayer$EventListener" on path: DexPathList[[zip file "/data/app/com.rntrackplayercrash-1/base.apk"],nativeLibraryDirectories=[/data/app/com.rntrackplayercrash-1/lib/x86, /data/app/com.rntrackplayercrash-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
03-27 09:52:26.336 26202 26202 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
03-27 09:52:26.336 26202 26202 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
03-27 09:52:26.336 26202 26202 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
03-27 09:52:26.336 26202 26202 I art     :   at void guichaguri.trackplayer.logic.services.PlayerService.onCreate() (PlayerService.java:74)
03-27 09:52:26.336 26202 26202 I art     :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3162)
03-27 09:52:26.336 26202 26202 I art     :   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
03-27 09:52:26.336 26202 26202 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1550)
03-27 09:52:26.336 26202 26202 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
03-27 09:52:26.336 26202 26202 I art     :   at void android.os.Looper.loop() (Looper.java:154)
03-27 09:52:26.336 26202 26202 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
03-27 09:52:26.336 26202 26202 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
03-27 09:52:26.336 26202 26202 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:866)
03-27 09:52:26.336 26202 26202 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:756)

**Comment by RekarBotany** [comment] 2018-03-27 10:18
i have the same problem , and its caused by google play services version
i have firebase that uses a version of play services which track player doesn't support

and it is all because of the cast feature , i want to remove it from the module

**Comment by binary1101** [comment] 2018-03-27 13:01
Same for me. Can't make it work with sdk 26. Worst of all I have both react-native-track-player and react-native-fbsdk. So I can't downgrade sdk, because react-native-fbsdk requires sdk 26.

**Comment by RekarBotany** [comment] 2018-03-27 13:17
Just try to remove cast feature. Follow the native event branch
And search the commits for removed cast feature

It is solved for me

**Comment by RekarBotany** [comment] 2018-03-27 13:20
[react-native-track-player.zip](https://github.com/react-native-kit/react-native-track-player/files/1852117/react-native-track-player.zip)

remove track player from node modules, and extract this in node modules

**Comment by Guichaguri** [comment] 2018-03-27 14:03
@RekarBotany In the dev branch, the Cast support was removed to be moved to a new package.
The problem seems to be the support lib, which has to be updated to API level 26. I started updating it in #165

**Comment by darrenchiu** [comment] 2018-04-09 02:26
just curious, when are we planning to have #165 released?

**Comment by mnlbox** [comment] 2018-04-12 07:49
@Guichaguri Dev branch also didn't wok for me. I think we need #165 as a major fix.

**Comment by hqdai** [comment] 2018-07-30 09:47
hi @RekarBotany,
Thank you for your advise, I got same issue, but how can I disable google play services version?
in your zip file, I found that you command the line: 
// Google Cast (Update this when RN updates the support library to 25+)
    //compile 'com.google.android.gms:play-services-cast-framework:9.4.0'

I don't have this line in my project, still get this issue.

**Comment by mahmoudfelfel** [comment] 2018-08-29 23:31
I got this error and it was fixed by adding exoplayer-core to the app level Gradle file:
```
implementation 'com.google.android.exoplayer:exoplayer-core:r2.4.3'
```
Then clean your project and build again.

**Comment by dcvz** [comment] 2018-10-21 11:55
Should not be a problem with v1.0.0

**Closed by dcvz** 2018-10-21 11:55 UTC
