### ISSUE TITLE
setupPlayer, add and play is not working and throwing warning after TrackPlayer.destroy()

### ISSUE THREAD

**Issue by nisheetsun** [react-native-kit/react-native-track-player#596] opened 2019-05-17 18:56 UTC
# Configuration

  React Native Environment Info:

>     System:
>       OS: macOS 10.14.3
>       CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
>       Memory: 297.03 MB / 8.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
>       Yarn: 1.9.2 - /opt/local/bin/yarn
>       npm: 6.4.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       Android SDK:
>         API Levels: 23, 25, 26, 27, 28
>         Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
>     IDEs:
>       Android Studio: 3.2 AI-181.5540.7.32.5056338
>       Xcode: /undefined - /usr/bin/xcodebuild
>     npmPackages:
>       react: 16.8.3 => 16.8.3 
>       react-native: 0.59.8 => 0.59.8 
>     npmGlobalPackages:
>       react-native-video: 3.2.1
>       react-native-workers: 0.3.1

> "react-native-track-player": "1.1.4"

# Issue
On click of remote-stop, I am TrackPlayer.destroy(). Players stop and push notification gets closed as expected but after when I am doing setupPlayer, updateOptions, reset and play, it's throwing a warning as mentioned below.

_Possible Unhandled Promise Rejection(id: 1): Error: You attempted to set the key '()' with value "{id:"1111", "url":"https://drive.google.com/uc?...", title:"Longing", "artist":"David", artwork:"https://..."}" on an object that is meant to be immutable and has been frozen_
P.S. - I took the code from example folder of this repository. You can also run that to reproduce the same issue.

# Code

```
TrackPlayer.addEventListener('remote-stop', () => {
    TrackPlayer.destroy();
  })
```

**Comment by Guichaguri** [comment] 2019-05-19 16:18
Duplicate of #597

**Closed by Guichaguri** 2019-05-19 16:18 UTC
Labels: Duplicate
