### ISSUE TITLE
Update now playing lockscreen

### ISSUE THREAD

**Issue by maendamedia** [react-native-kit/react-native-track-player#388] opened 2019-01-09 13:21 UTC
How can i manage to update the now playing on for example lock screen, when i use a live stream? The initial track and artist is set but after changes in state these are not updatedz

**Comment by Guichaguri** [comment] 2019-01-10 00:57
Duplicate of #93. We are looking into #331 and #384 for that.

**Closed by Guichaguri** 2019-01-10 00:57 UTC
Labels: Duplicate
