### ISSUE TITLE
(iOS) Background player not having any affect on audio

### ISSUE THREAD

**Issue by bbarr** [react-native-kit/react-native-track-player#747] opened 2019-09-30 19:31 UTC
# Configuration
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.64 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

react-native-track-player version: ^2.0.0-rc13

# Issue
On iOS 12.4 I notice that while the audio continues playing in the background, none of the background player controls have any affect on the audio other than volume. Pausing and playing are maintaining state independently of the audio in my app.

**Comment by HessiPard** [comment] 2019-10-05 09:25
I Have this problem too ...

**Comment by AlexeyVlasenko** [comment] 2019-10-08 19:28
Same issue

**Comment by SteffeyDev** [comment] 2019-10-09 19:35
I have this issue on the latest version of iOS as well

**Comment by R3DST0RM** [comment] 2019-12-18 21:30
Same issue, were you able to solve it?

**Comment by illl48** [comment] 2019-12-27 20:50
react-native-track-player version: dev
not working on iOS 13 too

**Comment by R3DST0RM** [comment] 2019-12-27 20:54
> react-native-track-player version: dev
> not working on iOS 13 too

I can confirm that iOS 13 its not possible to play any track at all.

**Comment by illl48** [comment] 2019-12-29 09:35
@R3DST0RM could you give #820 a try?

**Comment by illl48** [comment] 2019-12-30 20:12
> > react-native-track-player version: dev
> > not working on iOS 13 too
> 
> I can confirm that iOS 13 its not possible to play any track at all.

@R3DST0RM Can you give #820 a try if you are workin on dev branch.

**Comment by R3DST0RM** [comment] 2019-12-30 23:59
I will test it tomorrow and report here

**Comment by ovr** [comment] 2020-01-04 11:46
Dear all!

Dont specify `^2.0.0-rc13` (version with `^`) because NPM will resolve this version by ASCI sort order and will install 2.0.0-rc9, there is a fix for this issue in `2.0.0-rc13`

Specify `2.0.0-rc13`, reinstall and check `package-lock.json` (what version is resolved)!

**Comment by Vitalik7** [comment] 2020-01-23 10:20
@ovr  @Guichaguri  I have issue in ```2.0.0-rc13``` version!
when I press the pause button on the background player, time stops but the track continues to play

**Comment by ovr** [comment] 2020-01-23 11:14
@Vitalik7 I've got this version in app and it works.

Did you specify background service with callback for 'remote-stop'?

**Comment by Vitalik7** [comment] 2020-01-23 14:13
@ovr Thanks) I really forgot to use this services! Now is working)

**Comment by JakeMotta** [comment] 2020-03-18 19:03
I'm having the same issue. I've swapped to 2.0.0-rc13, but only the time on lock-screen stops, not the actual audio. Not sure if I've failed to declare something, or if I've done something wrong... I did registerPlaybackService right after app registry as well. 

**Service.js**
`module.exports = async function () {
  TrackPlayer.addEventListener('remote-play', () => {
    console.log("hit background play")
    TrackPlayer.play();
  });

  TrackPlayer.addEventListener("remote-pause", (event) => {
    console.log("#DEBUG remote pause #", event);
    TrackPlayer.pause();
  });

  TrackPlayer.addEventListener('remote-next', () => {
    console.log("hit background skip")
    TrackPlayer.skipToNext();
  });
};`

**Component playing music:**
`await TrackPlayer.setupPlayer();
        TrackPlayer.updateOptions({
          capabilities: [
            TrackPlayer.CAPABILITY_PLAY,
            TrackPlayer.CAPABILITY_PAUSE,
            TrackPlayer.CAPABILITY_SKIP_TO_NEXT
          ],
          compactCapabilities: [
            TrackPlayer.CAPABILITY_PLAY,
            TrackPlayer.CAPABILITY_PAUSE,
            TrackPlayer.CAPABILITY_SKIP_TO_NEXT
          ],
          notificationCapabilities: [
            TrackPlayer.CAPABILITY_PLAY,
            TrackPlayer.CAPABILITY_PAUSE,
            TrackPlayer.CAPABILITY_SKIP_TO_NEXT
          ]
        });
`

**Comment by curiousdustin** [comment] 2020-04-24 17:29
https://github.com/react-native-kit/react-native-track-player/commit/d3400a475d8be146aa25696b5f014dd538e2dd86 should resolve this. Will get this into v2 soon.

**Closed by curiousdustin** 2020-04-24 17:29 UTC
