### ISSUE TITLE
Update Current Track

### ISSUE THREAD

**Issue by shiroze** [react-native-kit/react-native-track-player#507] opened 2019-03-22 07:50 UTC
![image](https://user-images.githubusercontent.com/6022114/54808209-1fa04e80-4cb2-11e9-80cc-2f9726e8b96f.png)

is there a way to Update current track Title, Artist, and Image ?

**Comment by Guichaguri** [comment] 2019-03-22 10:53
Duplicate of #93. This is already being worked on #465

**Closed by Guichaguri** 2019-03-22 10:53 UTC
Labels: Duplicate, Enhancement

**Comment by shiroze** [comment] 2019-03-25 02:04
Thanks @Guichaguri , the pull Request work for Android. but how about ios ?

**Comment by Guichaguri** [comment] 2019-03-25 11:45
The PR is still in the works, it won't be merged until we have iOS support fully working too.
