### ISSUE TITLE
How to  realize the Player mode (Repeat, Repeat all, Shuffle)

### ISSUE THREAD

**Issue by Goodem** [react-native-kit/react-native-track-player#585] opened 2019-05-09 07:24 UTC
# Configuration

The latest version of `react-native-track-player` 

# Issue
How to  realize the Player mode (Repeat, Repeat all, Shuffle)

**Comment by LiWeiQiangAndroid** [comment] 2019-05-10 12:47
android see: https://medium.com/google-exoplayer/repeat-modes-in-exoplayer-19dd85f036d3

setRepeatMode
and
setShuffleModeEnabled

**Comment by Guichaguri** [comment] 2019-05-15 00:38
It's not implemented at the moment. We do plan to add it in the near future.

Duplicate of #122

**Closed by Guichaguri** 2019-05-15 00:38 UTC
Labels: Duplicate

**Comment by LiWeiQiangAndroid** [comment] 2019-05-15 01:54
I've implemented it, but there seems to be a bug

**Comment by Mangirish-Bhagat** [comment] 2021-05-08 10:05
@LiWeiQiangAndroid  can you share the implimented code? or share the logic here of how you've implimented it ?
